export const cardList = [
    {
        id: 1,
        topic: 'Web design',
        title: 'Название задачи',
        date: '30.10.23',        
        status: 'Без статуса',
    },
    {
        id: 2,
        topic: 'Research',
        title: 'Название задачи',
        date: '30.10.23',
        status: 'Нужно сделать',
    },
    {
        id: 3,
        topic: 'Research',
        title: 'Название задачи',
        date: '30.10.23',
        status: 'В работе',
    },
    {
        id: 4,
        topic: 'Research',
        title: 'Название задачи',
        date: '30.10.23',
        status: 'Готово',
    },
    {
        id: 5,
        topic: 'Research',
        title: 'Название задачи',
        date: '30.10.23',        
        status: 'Без статуса',
    },
    {
        id: 6,
        topic: 'Web design',
        title: 'Название задачи',
        date: '30.10.23',        
        status: 'Без статуса',
    },
    {
        id: 7,
        topic: 'Copywriting',
        title: 'Название задачи',
        date: '30.10.23',        
        status: 'Без статуса',
    },
    {
        id: 8,
        topic: 'Copywriting',
        title: 'Название задачи',
        date: '30.10.23',        
        status: 'В работе',
    },
    {
        id: 9,
        topic: 'Web design',
        title: 'Название задачи',
        date: '30.10.23',        
        status: 'В работе',
    },
    {
        id: 10,
        topic: 'Research',
        title: 'Название задачи',
        date: '30.10.23',        
        status: 'Тестирование',
    },
]